#!/usr/bin/env bash

# Fuzzy selector for git commit hash ("sha")
# Needs to be put in your path and made executable for git to find it.
# Credits: https://github.com/christoomey/dotfiles/issues/105

set -e

# fuzzy-select the commit
target_commit="$(git log --oneline --decorate --all --color=always | fzf --ansi --no-sort --reverse --tiebreak=index)"

# slice out the SHA
commit_sha="${target_commit:0:7}"

if [[ $commit_sha =~ ^[0-9a-z]{7}$ ]]; then
  # echo the SHA and copy it to the pasteboard
  echo $commit_sha | pbcopy
  echo $commit_sha
fi
