# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: ssh
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: code --wait
# Aliases allow you to create nicknames for gh commands
aliases:
    aliases: alias list
    co: pr checkout
    open: repo view --web
    pv: pr view --web
    pc: pr create --web

