#!/usr/bin/env bash

# Description: cd to the top level of the current git repository
#
# Shell: POSIX compliant
# Author: Anna Arad

if git rev-parse --git-dir > /dev/null 2>&1; then
    . "$(dirname "$0")"/.nnn-plugin-helper
else
    printf "Not in a git repository"
    exit 1
fi
cd "$(git rev-parse --show-toplevel)"