# Don't print a new line at the start of the prompt
add_newline = false

# Make the prompt a single line
[line_break]
disabled = true

[git_branch]
symbol = " "
truncation_length = 25

[python]
symbol = " "
disabled = true

[ruby]
symbol = " "

# disabled modules
[battery]
disabled = true

[package]
disabled = true

[cmd_duration]
disabled = true
